# Generated by Django 5.2 on 2025-05-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_usercoursehistory_usercourserating_usercoursereview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercoursehistory',
            options={'verbose_name': 'user_course_history', 'verbose_name_plural': 'user_course_histories'},
        ),
        migrations.AlterModelOptions(
            name='usercourserating',
            options={'verbose_name': 'user_course_rating', 'verbose_name_plural': 'user_course_ratings'},
        ),
        migrations.AlterModelOptions(
            name='usercoursereview',
            options={'verbose_name': 'user_course_review', 'verbose_name_plural': 'user_course_reviews'},
        ),
    ]
