# Generated by Django 5.2 on 2025-05-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_usercoursehistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usercoursehistory',
            table='user_course_history',
        ),
        migrations.AlterModelTable(
            name='usercourserating',
            table='user_course_rating',
        ),
        migrations.AlterModelTable(
            name='usercoursereview',
            table='user_course_review',
        ),
    ]
