# Generated by Django 5.2 on 2025-05-02 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_usercoursehistory_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercoursehistory',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='usercoursehistory',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usercourserating',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='usercourserating',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usercoursereview',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='usercoursereview',
            old_name='user_id',
            new_name='user',
        ),
    ]
