# Generated by Django 5.2 on 2025-05-11 08:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_course_id_usercoursehistory_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoursehistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
